version: "2"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile

    #environment:
    #  NGINX_SERVER_NAME: localhost
    #  NGINX_UPSTREAM_NAME: php
    #  DRUPAL_VERSION: 8 # Allowed: 7, 8.

    ports:
     - "8181:80"